### ISSUE TITLE
Catch-response

### ISSUE THREAD

**Issue by dhki** [HYU-ICEWALL/2024-ICEWALL#1]
첫 번째 회합 당시 사용한 Fiddler를 이용해 response 메시지를 수정하고, 스크린샷을 찍어주세요!

과제 설명은 아래 링크를 통해 다시 확인할 수 있습니다.
[http://basic.study.icewall.org](http://basic.study.icewall.org)

- Fiddler에 패킷이 캡쳐되지 않는 경우, 인터넷 접속 기록/캐시를 삭제한 뒤 다시 시도해보세요
- 알 수 없는 형식으로 response가 도착하는 경우, decode 버튼을 눌러보세요
- 기한은 3월 26일 회합 전까지입니다

**Comment by kangtaeho7161** [comment]
![스크린샷 2024-03-20 075151](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163989191/c55382fd-c029-4073-8baf-e812befb8464)

**Comment by kmsrogerkim** [comment]
![icewall_ass1](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/140868405/f2a7410c-539b-497a-9b16-e358cf54dfa7)

**Comment by seonimm** [comment]
![과제1](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164364518/42f460b8-f68e-43be-986e-cb7ca3485edf)

**Comment by dandb3** [comment]
<img width="1198" alt="스크린샷 2024-03-23 오후 9 16 19" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/98573005/6c5fa62d-bf1e-4f7a-a239-2de5c94cc4b3">

**Comment by 0x51018** [comment]
<img width="1280" alt="스크린샷 2024-03-19 190035" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/104045531/b5bef3bb-cc09-4293-b391-8281a5c0112a">

**Comment by ComputSoft** [comment]
![assignment icewall org - Whale 2024-03-24 오후 10_09_00](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164045359/3a43a60c-522f-4752-8fd1-2c8c3510d2ba)

**Comment by SiyeonWi** [comment]
![스크린샷 2024-03-19 185859](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/94772484/c8f19bbf-6f48-4826-8689-5919cb82fb5c)

**Comment by kanghongsin** [comment]
<img width="794" alt="alert 수정" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/162068105/e3ba44d1-47cf-4787-93e0-802d8d83e6fa">

**Comment by wygbsr** [comment]
<img width="960" alt="assignment1" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/109030418/6d728af2-8599-4d87-ae9b-9a93176a6a5a">

**Comment by patterclaw7** [comment]
![보안스샷](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164472394/e212f138-9525-487a-a005-7ae5beee7c01)

**Comment by patterclaw7** [comment]
![보안스샷](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164472394/92ee5b2f-6608-494c-97a4-35e97cc9734c)

**Comment by ghost** [comment]
![image](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/159753338/3cde5b45-2a39-4c92-bf20-7bb27b2acf22)

**Comment by sj1022** [comment]
![Catch-response](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/81280510/afc257c6-3c79-4511-8520-904dd1aad409)

**Comment by hee2chan** [comment]
![아이스월 이름출력](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163995741/9165a77b-6598-48eb-af1c-bc4ba9af7b9f)

**Comment by kimseongah** [comment]
Hi

**Comment by Rhwngud** [comment]
![icewall 과제](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164476641/fe82c819-828f-4507-aa6c-9a8c1f8d952d)

**Comment by zlexzlex** [comment]
<img width="1280" alt="icewall_assignment1" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/84063885/62921358-6e5e-49d5-a6c3-33f1b1c0f533">

**Comment by wjdrkdals** [comment]
<img width="1512" alt="스크린샷 2024-03-25 오후 5 42 34" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164312557/6ccc893c-c30e-46da-b168-0b99ed11be96">

**Comment by muchan918** [comment]
<img width="625" alt="스크린샷 2024-03-19 191233" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/152022287/6d15b48f-0f39-48d5-988a-e9aa8f51e55b">

**Comment by epfkm44** [comment]
<img width="449" alt="image" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/154308778/0a78abd5-be9f-4aba-b56d-9eba925ed06f">

**Comment by Jihong0760** [comment]
![image](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163997459/8d595ef7-c450-46bd-a275-79468a50a259)

**Comment by JIWOO1113** [comment]
![스크린샷 2024-03-19 191108](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/162775644/1cba3815-f3c2-4077-8f17-3c28da039bb8)

**Comment by patterclaw7** [comment]
![Uploading 과제1.png…]()

**Comment by patterclaw7** [comment]
![과제1](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164472394/e7c82ce7-5a89-4c5c-aa1b-b81dca95a21b)

**Comment by 2016hong03** [comment]
![스크린샷 2024-03-25 205918](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163995319/745397d9-219d-4d92-8dbf-845982e7e222)

**Comment by kwon120** [comment]
![Uploading 240325_icewall.png…]()

**Comment by sui1958** [comment]
![icewall1주차과제_정민혁](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/153601194/085f1a7f-ee49-49eb-884a-22c4da0b6d10)

**Comment by sui1958** [comment]
![image](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/153601194/ac3b0f6e-0e3c-4dee-83ee-8ba978b4e137)

**Comment by mjkim3039** [comment]
![스크린샷 2024-03-20 134811](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/160750083/a5f2357e-cf8a-4e4f-8266-f8e761c4692c)

**Comment by gudtjd82** [comment]
![icewall_assignment1](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/88320026/f09c7030-e451-4afa-8dbc-6b8f65d4667e)

**Comment by MelonSeo** [comment]
![icewall 과제](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163336986/37e4fb6c-1ca7-4d0e-9ab8-47456311b6f0)

**Comment by dlaxoyn** [comment]
<img width="583" alt="스크린샷 2024-03-19 오후 7 27 44" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/81676408/adeed8b6-500d-41fd-a2df-2bba91fd7611">

**Comment by Lxomgns** [comment]
![image](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164475389/224a6d73-a568-4c27-b632-21ea066d8038)

**Comment by soragodong331** [comment]
![Uploading 20240326_005652.jpg…]()

**Comment by soragodong331** [comment]
![image](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/152052570/470b88d7-a0d0-49d9-9299-170453f011d5)

**Comment by tye021122** [comment]
![assignment icewall org - Chrome 2024-03-26 오전 2_14_39](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/79403226/50612f63-afea-4211-88e3-9a4588354dde)

**Comment by Hamsta66** [comment]
![image](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/136138879/1ed6b15c-f0ac-48e6-8afb-d7c2db34d8d7)

**Comment by SONKANG24** [comment]
![clip1711416489350](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163995559/8421f8f2-4b48-4b46-a15c-699543de77da)

**Comment by juri1135** [comment]
<img width="486" alt="스크린샷 2024-03-26 112148" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/81513165/793de509-0c2a-42e8-a8e7-d0b2ec348b79">

**Comment by dongyoon1026** [comment]
![Uploading clip1710842080450.png…]()

**Comment by choijiahn** [comment]
<img width="960" alt="화면 캡처 2024-03-26 141155" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/164128842/6d8d0463-478d-4146-a8e8-6fb86ea8ce53">

**Comment by perr0r** [comment]
![아이스월 과제 1](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/34785543/a2acac48-c783-465f-b10d-758165266db9)

**Comment by minhoYu123** [comment]
![Uploading icewall 과제1.PNG…]()

**Comment by minhoYu123** [comment]
![icewall 과제1](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/73944948/e26326b8-e696-4447-a04d-df9943dc8116)

**Comment by leezo-e** [comment]
<img width="1425" alt="icewall_lab1_이조에" src="https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/127174303/a9c125e3-3a86-4f72-b41f-c3bfd4221a35">

**Comment by skyjwon1** [comment]
![IMG_1765](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/163995472/e44de9d7-2074-4e65-bf32-35a8ecd4f26d)

**Comment by myyh1234** [comment]
![스크린샷 2024-03-19 184343](https://github.com/HYU-ICEWALL/2024-ICEWALL/assets/43689495/577c1885-186d-4b73-860a-23b347635d4d)
